services:
  steganography-app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - ./src:/src
      - ./build:/build
      - /tmp/.X11-unix:/tmp/.X11-unix
    working_dir: /build
    tty: true