version: "3.8"

services:
  steganography-backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app  # <-- Монтируем исходники внутрь контейнера
    ports:
      - "8080:8080"
    tty: true
    networks:
      - steganography-net

  steganography-frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    tty: true
    networks:
      - steganography-net
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8080
      - CHOKIDAR_USEPOLLING=true

  steganography-nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - steganography-backend
      - steganography-frontend
    networks:
      - steganography-net

networks:
  steganography-net:
    driver: bridge